[package]
name = "parser"
version = "0.1.0"
edition = "2021"

[dependencies]
derive_more = { version = "1.0.0-beta.6", features = ["error", "display", "from_str"] }

[dev-dependencies]
rstest = "0.21.0"